#
# _config.yml for jekyll-bootstrap-blank
#

exclude: [ "CNAME", "README.md", "LICENSE.txt", "UNLICENSE.txt", "tmp", "*.sh", "**/*_src*" ]
permalink: /blog/:year/:month/:day/:title/index.:output_ext
production_url: https://marekmansell.com
title: Marek Mansell 
markdown: kramdown
gems:
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

google_analytics_id: G-9Z7XCY900H
google_validation: LATER
bing_validation: LATER
yandex_validation: LATER
